In [2]:
import numpy as np
import pandas as pd

In [9]:
pd.DataFrame([1,2,3],columns=['A'],index= ['P','Q','R'])

   A
P  1
Q  2
R  3

In [13]:
pd.DataFrame({"Months":["march","april"],"Sales":[20,40]})

  Months  Sales
0  march     20
1  april     40

In [20]:
df=pd.DataFrame(np.random.randint(0,100,(2,2)))
df

    0   1
0  95  41
1  83  19

In [19]:
df.shape

(2, 2)

In [36]:
df=pd.read_csv("dataset.csv")
df.head(2)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,8/11/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.96,2,0.0,41.9136
1,2,CA-2016-152156,8/11/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.94,3,0.0,219.5820

In [37]:
df.tail(2)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
9992,9993,CA-2017-121258,26/2/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.60,4,0.0,13.320
9993,9994,CA-2017-119914,4/5/2017,9/5/2017,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.16,2,0.0,72.948

In [38]:
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit'],
      dtype='object')

In [39]:
df.index

RangeIndex(start=0, stop=9994, step=1)

In [43]:
df[['Row ID','Order ID','State']].head(2)

   Row ID        Order ID     State
0       1  CA-2016-152156  Kentucky
1       2  CA-2016-152156  Kentucky

In [55]:
df.iloc[2:6,:10]

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City
2,3,CA-2016-138688,12/6/2016,16/6/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles
3,4,US-2015-108966,11/10/2015,18/10/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale
4,5,US-2015-108966,11/10/2015,18/10/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale
5,6,CA-2014-115812,9/6/2014,14/6/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles

In [57]:
df.dtypes

Row ID             int64
Order ID          object
Order Date        object
Ship Date         object
Ship Mode         object
Customer ID       object
Customer Name     object
Segment           object
Country           object
City              object
State             object
Postal Code        int64
Region            object
Product ID        object
Category          object
Sub-Category      object
Product Name      object
Sales            float64
Quantity           int64
Discount         float64
Profit           float64
dtype: object

In [63]:
np.iinfo(np.int8)

iinfo(min=-128, max=127, dtype=int8)

In [65]:
int(np.finfo(np.float16).min)

-65504

In [71]:
df.select_dtypes(include=['int16','float64']).head(2)

    Sales  Discount    Profit
0  261.96       0.0   41.9136
1  731.94       0.0  219.5820

In [72]:
df.select_dtypes(include=['int64']).shape

(9994, 3)

In [75]:
df.select_dtypes(include=['object']).shape

(9994, 15)

In [76]:
df.select_dtypes(include=['float64']).shape

(9994, 3)

In [77]:
df.shape

(9994, 21)

In [90]:
df1=df.iloc[0:6,0:7].copy()
df1

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name
0,1,CA-2016-152156,8/11/2016,11/11/2016,Second Class,CG-12520,Claire Gute
1,2,CA-2016-152156,8/11/2016,11/11/2016,Second Class,CG-12520,Claire Gute
2,3,CA-2016-138688,12/6/2016,16/6/2016,Second Class,DV-13045,Darrin Van Huff
3,4,US-2015-108966,11/10/2015,18/10/2015,Standard Class,SO-20335,Sean O'Donnell
4,5,US-2015-108966,11/10/2015,18/10/2015,Standard Class,SO-20335,Sean O'Donnell
5,6,CA-2014-115812,9/6/2014,14/6/2014,Standard Class,BH-11710,Brosina Hoffman

In [91]:
df1.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name'],
      dtype='object')

In [96]:
df['Row ID'].min()

1

In [99]:
df[['Sales','Row ID']].min()

Sales     0.444
Row ID    1.000
dtype: float64

In [107]:
df[['Sales']].mean()

Sales    229.858001
dtype: float64

In [110]:
df['Customer Name'].str.upper().head(3)

0        CLAIRE GUTE
1        CLAIRE GUTE
2    DARRIN VAN HUFF
Name: Customer Name, dtype: object

In [119]:
df['Customer Name'].str.split('a').head(3)

0         [Cl, ire Gute]
1         [Cl, ire Gute]
2    [D, rrin V, n Huff]
Name: Customer Name, dtype: object

In [142]:
df1['Order ID'].str.pad(width=67,side='right',fillchar=":")

0    CA-2016-152156::::::::::::::::::::::::::::::::...
1    CA-2016-152156::::::::::::::::::::::::::::::::...
2    CA-2016-138688::::::::::::::::::::::::::::::::...
3    US-2015-108966::::::::::::::::::::::::::::::::...
4    US-2015-108966::::::::::::::::::::::::::::::::...
5    CA-2014-115812::::::::::::::::::::::::::::::::...
Name: Order ID, dtype: object